version: "3.9"
services:
  backend:
    build: ./backend
    container_name: zcomm-backend
    restart: always
    volumes:
      - /etc/letsencrypt/live/zcommapp.com/fullchain.pem:/app/server.crt:ro
      - /etc/letsencrypt/live/zcommapp.com/privkey.pem:/app/server.key:ro
    environment:
      - API_ENV=production
    ports:
      - "8080:8080" # or use 8443 with HTTPS (see instructions)
  frontend:
    build: ./frontend
    container_name: zcomm-frontend
    restart: always

  nginx:
    image: nginx:alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/build:/usr/share/nginx/html:ro
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
