events {}

http {
  server {
    listen 80;
    server_name zcommapp.com www.zcommapp.com;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    server_name zcommapp.com www.zcommapp.com;

    ssl_certificate /etc/letsencrypt/live/zcommapp.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/zcommapp.com/privkey.pem;

    location /api/ {
      proxy_pass http://zcomm-backend:8080/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
    }
    location = /service-worker.js {
      root /usr/share/nginx/html;
      try_files $uri =404;
      default_type application/javascript;
    }
    location / {
      root /usr/share/nginx/html;
      try_files $uri $uri/ /index.html;
    }
  }
}