// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {core} from '../models';
import {main} from '../models';

export function AddContact(arg1:string,arg2:string):Promise<void>;

export function ClearKeys():Promise<void>;

export function CreateAccount(arg1:string,arg2:string):Promise<void>;

export function CreateAndSendDispatch(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function CreateZID(arg1:string):Promise<string>;

export function GetBasketCounts():Promise<Record<string, number>>;

export function GetBasketDispatches(arg1:string):Promise<Array<core.BasketDispatch>>;

export function GetConversation(arg1:string):Promise<main.Conversation>;

export function GetConversations(arg1:boolean):Promise<Array<main.ConvSummary>>;

export function GetDispatch(arg1:string):Promise<core.Dispatch>;

export function HandleDispatchAction(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<void>;

export function IsOnline():Promise<boolean>;

export function ListContacts():Promise<Array<main.Contact>>;

export function Login(arg1:string,arg2:string):Promise<Array<string>>;

export function Logout():Promise<void>;

export function RemoveContact(arg1:string):Promise<void>;

export function ResolveAlias(arg1:string):Promise<string>;

export function SelectZID(arg1:string):Promise<void>;

export function ToggleConversationArchive(arg1:string,arg2:boolean):Promise<void>;
