// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddContact(arg1, arg2) {
  return window['go']['main']['App']['AddContact'](arg1, arg2);
}

export function ClearKeys() {
  return window['go']['main']['App']['ClearKeys']();
}

export function CreateAccount(arg1, arg2) {
  return window['go']['main']['App']['CreateAccount'](arg1, arg2);
}

export function CreateAndSendDispatch(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateAndSendDispatch'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateZID(arg1) {
  return window['go']['main']['App']['CreateZID'](arg1);
}

export function GetBasketCounts() {
  return window['go']['main']['App']['GetBasketCounts']();
}

export function GetBasketDispatches(arg1) {
  return window['go']['main']['App']['GetBasketDispatches'](arg1);
}

export function GetConversation(arg1) {
  return window['go']['main']['App']['GetConversation'](arg1);
}

export function GetConversations(arg1) {
  return window['go']['main']['App']['GetConversations'](arg1);
}

export function GetDispatch(arg1) {
  return window['go']['main']['App']['GetDispatch'](arg1);
}

export function HandleDispatchAction(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['HandleDispatchAction'](arg1, arg2, arg3, arg4, arg5);
}

export function IsOnline() {
  return window['go']['main']['App']['IsOnline']();
}

export function ListContacts() {
  return window['go']['main']['App']['ListContacts']();
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RemoveContact(arg1) {
  return window['go']['main']['App']['RemoveContact'](arg1);
}

export function ResolveAlias(arg1) {
  return window['go']['main']['App']['ResolveAlias'](arg1);
}

export function SelectZID(arg1) {
  return window['go']['main']['App']['SelectZID'](arg1);
}

export function ToggleConversationArchive(arg1, arg2) {
  return window['go']['main']['App']['ToggleConversationArchive'](arg1, arg2);
}
