/* eslint-disable no-restricted-globals */

// This is the 'service-worker.js' template for Create React App PWA support.
// It is processed by Workbox at build time.

import { clientsClaim } from "workbox-core";
import { precacheAndRoute, createHandlerBoundToURL } from "workbox-precaching";
import { NavigationRoute, registerRoute } from "workbox-routing";

clientsClaim();

// Precache all of the assets generated by your build process.
precacheAndRoute(self.__WB_MANIFEST);

const handler = createHandlerBoundToURL(process.env.PUBLIC_URL + "/index.html");
const navigationRoute = new NavigationRoute(handler, {
  denylist: [/^\/api\//], // Prevents API calls from being intercepted by the SW
});
registerRoute(navigationRoute);
